### ISSUE TITLE
windows installer job failure

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#251]
Just to keep track of this failure :
job 8274 : 5 oct. 2020 23:28
> Building setup translation for culture "zh-cn" with LangID "2052"...
Windows Installer XML Toolset Linker version 3.14.0.3910
Copyright (c) .NET Foundation and contributors. All rights reserved.
Package language = 2052, ProductLanguage = 2052, Database codepage = 936
Done
1031
1036
1041
2052
3082
Building setup translation for culture "zh-tw" with LangID "1028"...
Windows Installer XML Toolset Linker version 3.14.0.3910
Copyright (c) .NET Foundation and contributors. All rights reserved.
light.exe : error LGHT0001 : Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
Exception Type: System.Runtime.InteropServices.COMException
Stack Trace:
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Xml.XmlConfiguration.XmlReaderSection.get_ProhibitDefaultUrlResolver()
   at System.Xml.Schema.XmlSchemaCollection..ctor(XmlNameTable nametable)
   at System.Xml.XmlValidatingReaderImpl..ctor(XmlReader reader)
   at System.Xml.XmlValidatingReader..ctor(XmlReader reader)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(Stream stream, Uri uri, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(String path, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
light failed with : 1
Failed to generate setup translation of culture "zh-tw" with LangID "1028".
failed to build translation zh-tw 1028
Build step 'Execute Windows batch command' marked build as failure
Archiving artifacts
[Checks API] No suitable checks publisher found.
[Slack Notifications] found #8279 as previous completed, non-aborted build
[Slack Notifications] will send OnEveryFailureNotification because build matches and user preferences allow it
Finished: FAILURE

**Comment by douph1** [comment]
and same error with another language pack
job 8280

> Building setup translation for culture "es-es" with LangID "3082"...
Windows Installer XML Toolset Linker version 3.14.0.3910
Copyright (c) .NET Foundation and contributors. All rights reserved.
Package language = 3082, ProductLanguage = 3082, Database codepage = 1252
Done
1031
3082
Building setup translation for culture "fr-fr" with LangID "1036"...
Windows Installer XML Toolset Linker version 3.14.0.3910
Copyright (c) .NET Foundation and contributors. All rights reserved.
light.exe : error LGHT0001 : Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
Exception Type: System.Runtime.InteropServices.COMException
Stack Trace:
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Xml.XmlConfiguration.XmlReaderSection.get_ProhibitDefaultUrlResolver()
   at System.Xml.Schema.XmlSchemaCollection..ctor(XmlNameTable nametable)
   at System.Xml.XmlValidatingReaderImpl..ctor(XmlReader reader)
   at System.Xml.XmlValidatingReader..ctor(XmlReader reader)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(Stream stream, Uri uri, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(String path, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
light failed with : 1
Failed to generate setup translation of culture "fr-fr" with LangID "1036".
failed to build translation fr-fr 1036
Build step 'Execute Windows batch command' marked build as failure
Archiving artifacts
[Checks API] No suitable checks publisher found.
[Slack Notifications] found #8273 as previous completed, non-aborted build
[Slack Notifications] will send OnEveryFailureNotification because build matches and user preferences allow it
Finished: FAILURE

**Comment by douph1** [comment]
Both job failure on  build-azure-win2012r2-x64-1

**Comment by douph1** [comment]
another build failure on **build-azure-win2012r2-x64-1**  job 9239 at 04/11/2020 06:15


>Main-OpenJDK16-jre_x86-32_windows_hotspot-16.0.0.22.wxs
Files-OpenJDK16-jre_x86-32_windows_hotspot-16.0.0.22.wxs
LIGHT
Windows Installer XML Toolset Linker version 3.14.0.3910
Copyright (c) .NET Foundation and contributors. All rights reserved.
light.exe : error LGHT0001 : Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
Exception Type: System.Runtime.InteropServices.COMException
Stack Trace:
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Xml.XmlConfiguration.XmlReaderSection.get_ProhibitDefaultUrlResolver()
   at System.Xml.Schema.XmlSchemaCollection..ctor(XmlNameTable nametable)
   at System.Xml.XmlValidatingReaderImpl..ctor(XmlReader reader)
   at System.Xml.XmlValidatingReader..ctor(XmlReader reader)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(Stream stream, Uri uri, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Localization.Load(String path, TableDefinitionCollection tableDefinitions, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
Failed to links and binds one or more .wixobj files and creates a Windows Installer database (.msi or .msm)
J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix>EXIT /b 2

**Comment by douph1** [comment]
Jenkins : log history extended to 7 days
Need to look into Windows Event log on the next event

**Comment by douph1** [comment]
No new event from this since long time maybe resolved by @sxa  action:
>There are some permissions issue related to the jenkins agent in the system log (I've now resolved the underlying problem causing that)
